# Example

In [14]:
import numpy as np 

## List comprehension way

In [5]:
cat = np.random.randint(4, size=10)
cat

array([2, 2, 1, 3, 3, 3, 2, 1, 2, 0])

In [16]:
k_0 = np.array([x==0 for x in cat]).astype(int)
k_0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [11]:
k_1 = np.array([x==1 for x in cat]).astype(int)
k_1

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [12]:
k_2 = np.array([x==2 for x in cat]).astype(int)
k_2

array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [13]:
k_3 = np.array([x==3 for x in cat]).astype(int)
k_3

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

## Casting the array way 

In [19]:
K_0 = (cat == 0) * 1
K_0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [20]:
K_1 = (cat == 1) * 1
K_1

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [21]:
K_2 = (cat == 2) * 1
K_2

array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [22]:
K_3 = (cat == 3) * 1
K_3

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])