In [102]:
import time
import pickle
import random
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
import scipy.optimize as op

In [101]:
def sigmoid(x):
    # Activation function used to map any real value between 0 and 1
    return 1 / (1 + np.exp(-x))

def cost_function(theta, x, y):
    # Computes the cost function for all the training samples
    m = x.shape[0]
    total_cost = -(1 / m) * np.sum(
        y * np.log(probability(theta, x)) + (1 - y) * np.log(
            1 - probability(theta, x)))
    return total_cost

def feed_forward(thetas, X): #(60000, 784)
    a = [X]
    for i in range(len(thetas)):
        a.append(
            sigmoid(
                np.matmul(
                    np.hstack((
                        np.ones(len(X)).reshape(len(X), 1),
                        a[i]
                    )),
                    thetas[i].T
                )
            )
        )
    return a;

def inflate_matrixes(flat_thetas, shapes):
    layers = len(shapes) + 1
    sizes = [shape[0] * shape[1] for shape in shapes]
    steps = np.zeros(layers, dtype=int)
    
    for i in range(layers - 1):
        steps[i + 1] = steps[i] + sizes[i]
        
    return [
        np.array(flat_thetas[steps[i]: steps[i + 1]]).reshape(*shapes[i])
        for i in range(layers - 1)
    ]
    

In [ ]:
def jacobian(flat_thetas, shapes, X, Y):
    m, layers = len(X), len(shapes) + 1
    thetas = inflate_matrixes(flat_thetas, shapes)
    a = feed_forward(thetas, X)
    deltas = [*range(layers - 1), a[-1] - Y]
    
    #backward_prop
    #for i in range(layers - 2, 0, -1):
    
    #return flatten_list([
    #    ...
    #])
    
def backward_prop(thetas, X, Y):
    m,_ = X.shape
    delta = copy.deepcopy(thetas)
    for i in delta: 
        i[:] = 0
    a = feed_forward(thetas, X)
    first_delta = a[-1] - Y.T
    deltas = [first_delta]
    #backward_prop
    for i in reversed(range(1, len(thetas))):
        first_delta = np.multiply(
            np.matmul(thetas[i].T[1:,:], first_delta),
            np.multiply(a[i], (1-a[i]))
            )
    deltas.append(first_delta)
    
    

In [71]:
def flatten_list(thetas):
    flat = np.array([])
    for i in thetas:
        flat = np.append(flat, i.flatten())
    flat.flatten()
    return flat

In [12]:
hiddenNeurons = 100
outputNeurons = 10


In [40]:
from utils import mnist_reader
X_train, y_train = mnist_reader.load_mnist('data/fashion', kind='train')
X_test, y_test = mnist_reader.load_mnist('data/fashion', kind='t10k')
m, n = X_train.shape
Y_train = pd.get_dummies(y_train)
Y_test = pd.get_dummies(y_test)

In [98]:
norm = MinMaxScaler()

X_train_scale = norm.fit_transform(X_train)

In [52]:
"""
theta_shapes = np.array([
    [hiddenNeurons, n + 1],
    [outputNeurons, hiddenNeurons + 1]
])
theta_shapes
"""
NETWORK_ARCHITECTURE = np.array([
    n,
    130,
    10
])

theta_shapes = np.hstack((
    NETWORK_ARCHITECTURE[1:].reshape(len(NETWORK_ARCHITECTURE) - 1, 1),
    (NETWORK_ARCHITECTURE[:-1] + 1).reshape(len(NETWORK_ARCHITECTURE) - 1, 1)
))
theta_shapes

array([[130, 785],
       [ 10, 131]])

In [75]:
flat_thetas = flatten_list([
    np.random.rand(*theta_shape)
    for theta_shape in theta_shapes
])
#flat_thetas.shape
flat_thetas

array([0.95758276, 0.111002  , 0.05270495, ..., 0.15731434, 0.36717727,
       0.58390721])

In [79]:
thetas = np.array(inflate_matrixes(
    flat_thetas,
    theta_shapes
))
thetas.shape

(2,)

In [100]:
# Predict
a = feed_forward(thetas, X_train_scale)
a

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]),
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]])]

array([0], dtype=int64)